# 1. Create a 3x3x3 array with random values 

In [92]:
import numpy as np
import sys

In [90]:
x = np.random.random((4,3,3))
print(x)
x.shape

[[[0.72386667 0.03709029 0.70487086]
  [0.04684828 0.52609215 0.81577999]
  [0.7547352  0.9900568  0.72503081]]

 [[0.77416728 0.03864463 0.94911317]
  [0.14881776 0.64593413 0.68861926]
  [0.98903566 0.49743242 0.50688355]]

 [[0.59454674 0.33274831 0.56136252]
  [0.14942031 0.57594132 0.1960504 ]
  [0.50224533 0.24178665 0.38202036]]

 [[0.75807021 0.1341758  0.76467623]
  [0.30561124 0.43502994 0.10088294]
  [0.23691948 0.56008362 0.9622551 ]]]


(4, 3, 3)

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [21]:
y = np.diag([1, 2, 3, 4])
print(y)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [220]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))

print("8x8 Matrix - Checkerboard pattern:", "\n")
print (Z)

8x8 Matrix - Checkerboard pattern: 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [42]:
a= np.random.random((5,5))
print("Original array:")
print(a, "\n")

amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
print("After normalization:")
print(a)

Original array:
[[0.46756076 0.01728663 0.0314303  0.60432411 0.16369619]
 [0.69178857 0.68917125 0.28005752 0.71421174 0.99061662]
 [0.34825956 0.0934192  0.7065663  0.46063794 0.72666213]
 [0.33274705 0.10465019 0.67819612 0.88058603 0.4070797 ]
 [0.47074889 0.39533004 0.68949025 0.07476071 0.08687686]] 

After normalization:
[[0.46261199 0.         0.01453122 0.60312277 0.1504213 ]
 [0.69298383 0.69029479 0.26997103 0.71602142 1.        ]
 [0.34004185 0.07821867 0.70816648 0.45549949 0.72881295]
 [0.32410429 0.0897574  0.67901893 0.88695449 0.40047371]
 [0.46588748 0.3884021  0.69062253 0.05904892 0.07149706]]


# 5.  How to find common values between two arrays?

In [47]:
array1 = np.array([0,10,20,40,60])
print("first_Array: ",array1)

array2 = np.array([10,30,40,50,70])
print("Second_Array: ",array2, "\n")

print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

first_Array:  [ 0 10 20 40 60]
Second_Array:  [10 30 40 50 70] 

Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [17]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print("Yestraday is: ",yesterday)

today     = np.datetime64('today')
print("Today is: ",today)

tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Tomorrow is: ",tomorrow)

Yestraday is:  2020-07-25
Today is:  2020-07-26
Tomorrow is:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [65]:
x = np.random.randint(0,6,10)
print("First array:")
print(x, "\n")

y = np.random.randint(0,6,10)
print("Second array:")
print(y, "\n")



print("Test to see if the above arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[5 5 5 5 1 1 0 5 2 4] 

Second array:
[1 0 2 5 0 0 4 5 5 1] 

Test to see if the above arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [78]:
xc = np.random.random(10)
print("Original array:")
print(xc, "\n")

xc[xc.argmax()] = -1
print("Maximum value replaced by -1:")
print(xc)

Original array:
[0.0578475  0.85989908 0.77166749 0.8484862  0.90771435 0.80197083
 0.52533496 0.4431915  0.09966962 0.95534894] 

Maximum value replaced by -1:
[ 0.0578475   0.85989908  0.77166749  0.8484862   0.90771435  0.80197083
  0.52533496  0.4431915   0.09966962 -1.        ]


# 9. How to print all the values of an array?

In [226]:
np.set_printoptions(threshold=sys.maxsize)
lagos = np.zeros((14, 14))
print(lagos)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [114]:
print("Original matrix:\n")
Xe = np.random.rand(7, 6)
print(Xe)

print("\nSubtract the mean of each row of the said matrix:\n")
Y = Xe - Xe.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.33183421 0.85674291 0.20307283 0.83901579 0.93303422 0.88648336]
 [0.32316476 0.70390754 0.91821973 0.0147501  0.2662875  0.61486178]
 [0.15555789 0.0823811  0.10627615 0.86868989 0.44801108 0.13039953]
 [0.55835424 0.16669086 0.11355352 0.42889976 0.62865018 0.44331895]
 [0.43432669 0.08858767 0.51139624 0.13850785 0.78640185 0.03441348]
 [0.00793408 0.3485245  0.17964546 0.17055393 0.06299433 0.94038165]
 [0.12511598 0.1566066  0.66568778 0.42140419 0.08474381 0.00861531]]

Subtract the mean of each row of the said matrix:

[[-0.34319634  0.18171236 -0.47195772  0.16398523  0.25800367  0.21145281]
 [-0.15036714  0.23037564  0.44468783 -0.4587818  -0.2072444   0.14132988]
 [-0.14299472 -0.2161715  -0.19227646  0.57013729  0.14945847 -0.16815307]
 [ 0.16844299 -0.22322039 -0.27635773  0.03898851  0.23873893  0.0534077 ]
 [ 0.1020544  -0.24368463  0.17912394 -0.19376445  0.45412955 -0.29785881]
 [-0.27707158  0.06351884 -0.1053602  -0.11445173 -0.22201133  0.655376


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [228]:
xxx = np.ones(10)
yyy = np.random.randint(0,len(xxx),20)

xxx += np.bincount(yyy, minlength=len(xxx))
print(xxx)

[5. 4. 1. 2. 3. 1. 2. 5. 4. 3.]


# 12.How to get the diagonal of a dot product?

In [126]:
a = np.arange(15).reshape(5, 3)
b = np.arange(9).reshape(3, 3)
print(a, "\n")
print(b, "\n")

c = np.diag(np.dot(np.dot(a, b), a.T))
print (c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[  60  672 1932 3840 6396]


# 13.How to find the most frequent value in an array?

In [135]:
xn = np.random.randint(0, 15, 20)
print("Original array:")
print(xn,"\n")

print("Most frequent value in the above array:")
print(np.bincount(xn).argmax())


Original array:
[ 3 11  9 11 11  6  6  7  1  4 11  1  0  0  6 11  9  2  4  7] 

Most frequent value in the above array:
11


# 14.How to get the n largest values of an array

In [164]:
xq = np.random.randint(0,199,20)
print("Original array:")
print(xq, "\n")

print("largest values of an array: ")
print (xq[np.argsort(xq)[-1:]])


Original array:
[ 25 109 105  78 195 117 140   6 101  57  51 164 159 143  37  98 198 195
 180  21] 

largest values of an array: 
[198]


# 15.How to create a record array from a regular array?

In [174]:
xx=np.array([4,7,9,3])
print("First array:", xx,"\n")

yy=np.array(['Red','Green','Blue','Yellow'])
print("Second array:",yy,"\n")

zz=np.array([13.20,98,77,120])
print("Third array:",zz,"\n")

result= np.core.records.fromarrays([xx, yy, zz],names='a,b,c')

print("A record array from a regular array:")
print(result[0])
print(result[1])
print(result[2])
print(result[3])

First array: [4 7 9 3] 

Second array: ['Red' 'Green' 'Blue' 'Yellow'] 

Third array: [ 13.2  98.   77.  120. ] 

A record array from a regular array:
(4, 'Red', 13.2)
(7, 'Green', 98.)
(9, 'Blue', 77.)
(3, 'Yellow', 120.)
